version: '3'

networks:
  database:
    internal: true
  public:

services:
  yessir-db:
    container_name: yessir-db
    image: bitnami/postgresql:16.3.0-debian-12-r14
    environment:
      POSTGRES_DB: 'yessir'
      POSTGRES_USER: 'yessir'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'
      POSTGRES_ROOT_HOST: '%'
    volumes:
      - './yessir-database/postgresql:/bitnami/postgresql'
    networks:
      - database
    expose:
      - 5432
    restart: unless-stopped

  yessir-api:
    container_name: yessir-api
    image: docker.io/brunovitalino/yessir-api-image:latest
    environment:
      DATABASE_HOST: 'yessir-db'
    ports:
      - 8080:80
    networks:
      - database
      - public
    restart: unless-stopped
    depends_on:
      - yessir-db
    healthcheck:
      test: "curl -sS http://yessir-api:80/actuator/health"
      interval: 30s
      timeout: 5s
      retries: 3
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
  yessir-interface:
    container_name: yessir-interface
    image: docker.io/brunovitalino/yessir-interface-image:latest
    environment:
      API_URL: 'http://localhost:8080'
    ports:
      - 4200:80
    networks:
      - public
    restart: unless-stopped
    depends_on:
      - yessir-api

